### ISSUE TITLE
Allow making Cython declarations available to C include files

### ISSUE THREAD

**Issue by scoder** [cython/cython#2079]
Currently, all header files are included before the Cython file declarations in order to make external types available for the Cython code. In some cases, however, it's desirable to also make declarations in Cython code available to C include files.

Attempts so far: #1650, #1896

**Comment by scoder** [comment]
One idea is to add an explicit declaration or directive after all, but we could also move includes behind Cython declarations if they actually occur behind Cython declarations in the user code. I.e., if you write this:
```
cdef extern from "abc.h": ...
ctypedef int huhu
cdef extern from "xyz.h": ...
```
then `abc.h` would be an early include and `xyz.h` would be a late include that could thus make use of `huhu`. That way, it is at least visible in the code what goes on.

**Comment by jdemeyer** [comment]
Personally, I have always been of the opinion that explicit syntax is the best solution. Something like
```
cdef extern from "abc.h" late
```
or the proposal from #1650 
```
cdef extern from "|abc.h"
```

**Comment by jdemeyer** [comment]
I don't understand what you mean with the 4 cases. Why should cimported declarations and local declarations be treated differently here? My pull request #1650 didn't make that difference but it solved the problem anyway.

**Comment by scoder** [comment]
I think I would find it surprising if a cimported include file ended up behind local declarations. It seems more intuitive if (transitively) cimported declarations came in one block, rather than being subject to the early-late split. As a module author, I do not control cimports, so their declarations shouldn't interfere with my code. (And now you are going to tell me that that breaks your use case, right?)

In any case, all I really want is a solution that:
- avoids breaking existing code (if possible)
- makes it clear where the order comes from
- makes it easy and obvious to repair code that misbehaves under the new semantics

IMHO, the current implementation provides none of those three.

**Comment by jdemeyer** [comment]
> It seems more intuitive if (transitively) cimported declarations came in one block, rather than being subject to the early-late split.

So if I understand you correctly, there shouldn't be an early/late split at all, declarations (for anything: both extern and non-extern declarations) should appear in the generated C file in the order that they appear in the sources (whatever that means)?

My use case is essentially
```
cdef void foo()  # Implemented in Cython

cdef extern from "something.h":
   void extern_function_calling_foo()  # Calls foo()
```
and the same for `cdef` variables instead of functions. So I guess that your proposal would work for me.

Now the practical question becomes: how realistic is it to actually implement that? As you know, I would be really disappointed if this feature would be dropped for Cython 0.28 and postponed until "whenever".

**Comment by scoder** [comment]
I'm sorry Jeroen. I do understand the need for this feature and I'd be happy to have it in Cython, but the only reason why 0.28 is still held back and has not been released mid-December are the visible drawbacks of the current implementation. If it's takes longer to implement a good solution, then I'd rather see that time invested properly than releasing something now, forcing users to adapt their code, and then rendering that effort useless again by removing it in the next release.

**Comment by jdemeyer** [comment]
And how about the "explicit syntax" proposal that I mentioned a few times? That is easy to implement, it works, it doesn't break existing code. For all I care, you don't even have to document it if you don't want to make it too "official".

**Comment by scoder** [comment]
I'd prefer first having an idea of how much effort it is to implement this nicely. We probably still have a couple of weeks until 0.28 and its first bug-fix release are out.

**Comment by jdemeyer** [comment]
Another idea (just brainstorming...): keep the current "auto late include" behaviour but enable it depending on some compiler directive.

**Comment by scoder** [comment]
I added a preliminary directive for 0.28, just to keep this feature usable. It *will* be removed in a future release.

**Comment by jdemeyer** [comment]
> It will be removed in a future release.

What do you mean exactly? Is the plan to keep the feature of late includes but just replacing this directive by some other implementation? I could live with that.

**Comment by scoder** [comment]
> Is the plan to keep the feature of late includes but just replacing this directive by some other implementation?

Yes. I would like to get rid of the directive again (thus the name), keep the general feature, but replace the implementation with something that is obvious from the code. You may take the directive as a present. Happy coding, and thank you for your continuous contributions.

**Comment by scoder** [comment]
Marking as release blocker for Cython 3.0 for replacing the directive.

**Comment by jdemeyer** [comment]
So what's the plan here? After the discussion last time, we settled with the directive because we couldn't agree on a different way to implement the feature.

**Comment by 0dminnimda** [comment]
Was this issue resolved in #1896?
So the only thing to do is not remove `preliminary_late_includes_cy28`?

**Comment by scoder** [comment]
The issue is still unresolved and the directive is still available.

I'll remove the "blocker" tag, though. The directive is clearly a deprecated feature and we can remove it at any time in the future when we find a better implementation. (Don't expect that to happen soon, but if someone wants to invest the time, I'll be happy to accept a replacement.)

**Comment by 0dminnimda** [comment]
Also I guess that #1997 needs to be mentioned here as well
