### ISSUE TITLE
Weird behavior when iterating over list of dicts

### ISSUE THREAD

**Issue by bolind** [cython/cython#2339]
When trying to cython3 the following code:

```
def foo():
    myDict1 = {"a": 1, "b": 2}
    myDict2 = {"c": 3, "d": 4}
    for i in [myDict1, myDict2]:
        for key, value in i.items():
            print(key, value)

foo()
```
I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/cython3", line 8, in <module>
    main(command_line = 1)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 704, in main
    result = compile(sources, options)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 679, in compile
    return compile_multiple(source, options)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 657, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 487, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Pipeline.py", line 328, in run_pipeline
    data = phase(data)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ModuleNode.py", line 118, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ModuleNode.py", line 339, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 436, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 3056, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 1923, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 1681, in generate_function_body
    self.body.generate_execution_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 442, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 6194, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 442, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Nodes.py", line 6190, in generate_execution_code
    self.iterator.generate_evaluation_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ExprNodes.py", line 627, in generate_evaluation_code
    self.generate_subexpr_evaluation_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ExprNodes.py", line 642, in generate_subexpr_evaluation_code
    node.generate_evaluation_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ExprNodes.py", line 633, in generate_evaluation_code
    self.generate_result_code(code)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ExprNodes.py", line 4944, in generate_result_code
    if func_type is not type_type and not self.arg_tuple.args and self.arg_tuple.is_literal:
AttributeError: 'NoneType' object has no attribute 'args'
```

Meanwhile, the python code works fine and none of my usual linter stuff can find any issues with this...

Error is present both with cython3 0.23.4 and 0.26.1.

**Comment by gabrieldemarmiesse** [comment]
By default, Cython uses the python 2 semantics (I know it can be confusing). My guess is that Cython noticed that you had dictionaries and tried to optimize this, since dictionaries don't have an `item()` function in python 2, the compiler crashed. The solution in your case is to do this:

```python
# cython: language_level=3

def foo():
    myDict1 = {"a": 1, "b": 2}
    myDict2 = {"c": 3, "d": 4}
    for i in [myDict1, myDict2]:
        for key, value in i.items():
            print(key, value)

foo()
```

Discussion is ongoing in the dev mailing list to solve this unexpected behavior.

**Comment by bolind** [comment]
Ah, interesting. Thanks for your reply. For the record, calling cython(3) with "-3" also does the trick.

**Comment by scoder** [comment]
In any case, the compiler shouldn't crash here, but I think I recall that there was a bug like that fixed in recent versions.

**Comment by gabrieldemarmiesse** [comment]
I tested it, and in the most recent commit of master, the compiler still crashes here on the "same" line.

```
Running tests against Cython 0.29a0 ff577a2baf4aebacd1a2f9bebd769e05e5d05ae1

...

ERROR: runTest (__main__.CythonCompileTestCase)
compiling (c) totest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/smith/Desktop/projects/cython/runtests.py", line 823, in runTest
    self.runCompileTest()
  File "/mnt/c/Users/smith/Desktop/projects/cython/runtests.py", line 829, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "/mnt/c/Users/smith/Desktop/projects/cython/runtests.py", line 1032, in compile
    self.run_cython(test_directory, module, workdir, incdir, annotate)
  File "/mnt/c/Users/smith/Desktop/projects/cython/runtests.py", line 934, in run_cython
    full_module_name=module)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Main.py", line 759, in compile
    return compile_single(source, options, full_module_name)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Main.py", line 708, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Main.py", line 499, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/ModuleNode.py", line 142, in process_implementation
    self.generate_c_code(env, options, result)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/ModuleNode.py", line 377, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 438, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 3164, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 1976, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 1738, in generate_function_body
    self.body.generate_execution_code(code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 444, in generate_execution_code
    stat.generate_execution_code(code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 6656, in generate_execution_code
    self.body.generate_execution_code(code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 444, in generate_execution_code
    stat.generate_execution_code(code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/Nodes.py", line 6652, in generate_execution_code
    self.iterator.generate_evaluation_code(code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/ExprNodes.py", line 714, in generate_evaluation_code
    self.generate_subexpr_evaluation_code(code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/ExprNodes.py", line 729, in generate_subexpr_evaluation_code
    node.generate_evaluation_code(code)
  File "/mnt/c/Users/smith/Desktop/projects/cython/Cython/Compiler/ExprNodes.py", line 5703, in generate_evaluation_code
    if not function.type.is_pyobject or len(self.arg_tuple.args) > 1 or (
AttributeError: 'NoneType' object has no attribute 'args'
```

**Comment by scoder** [comment]
Thanks for the test case. There's something weird going on during type inference/analysis.
