### ISSUE TITLE
Xcode 10.1 error when compiling C++ files

### ISSUE THREAD

**Issue by jsawruk** [cython/cython#2694]
I have a file abc.pyx that starts:
```
# distutils: language=c++
```
(because I am using vector).

This file compiled fine until I upgraded to Xcode 10.1 (10B61). I now get the following error:

```
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard
      library instead [-Wstdlibcxx-not-found]
abc.cpp:636:10: fatal error: 'ios' file not found
#include "ios"
         ^~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
```

All of my pyx files that are compiled using C instead of C++ are compiling correctly.

I am using Cython 0.29 in an Anaconda environment with Python 3.6.2 on macOS Mojave 10.14.1.
```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
```

My setup.py looks like:
```
setup(ext_modules=cythonize[(abc.pyx)])
```

I am building using the following command:
```
python setup.py build_ext --inplace
python setup.py install
```

Any suggestions would be greatly appreciated. Is there any way I can pass a compiler option to just those files?

This [StackOverflow response](https://stackoverflow.com/a/40031250) is close, but I don't want to compile all of my pyx files into C++. I tried that, but got other errors. It would be simplest if I could just resolve the issue of this single file.

**Comment by jsawruk** [comment]
This issue was resolved by upgrading to the Xcode Command Line Tools 10.1, released on November 2, 2018.

**Comment by rkingery** [comment]
This issue has not been resolved. I'm using Command Line Tools 10.14 (released Nov 2) with Mojave version 10.14, and I still get the same problems as before.

**Comment by jsawruk** [comment]
I am running Mojave 10.14.2 and no longer have this issue with the latest version of Command Line Tools (Nov 2). There might be some other issue with your environment, though I don't know what it might be.

**Comment by rkingery** [comment]
I tried completely uninstalling the command line tools, along with my python distribution (Anaconda with python 3.7), and reinstalling everything from scratch, and it gives the same problems. Only thing I can think of if it's not a cython issue is that it's somehow an anaconda issue (or something with python versions). Either way, using cython via Anaconda (with python 3.7) on Mojave doesn't appear to work.

**Comment by wyessen** [comment]
I am not sure why this was closed. There are two problems, it seems. One is with OSX LLVM setup, the other with Cython:

1. LLVM (on OSX) no longer supports `libstdc++`. So in your Cython setup script, just add `'-stdlib=libc++` in the `extra_compiled_flags` option, and that should compile.

2. The linker is still broken and requires linkage to `libc++` instread of `libstdc++`. 

The first problem can be fixed in the setup script. The second is more involved. I think it should be fixed in Cython proper.

**Comment by scoder** [comment]
Cython does not change anything in the flags and options of your C compiler or linker. The usual ways how these options enter the game are:
- provided by the user, e.g. by setting `CFLAGS`
- inherited from the original build flags of CPython itself in `distutils`
- platform/deployment specific configuration
AFAICT, none of the effects described in this ticket suggest a problem in Cython.

**Comment by joshlk** [comment]
Originally posted by @TruongKhang in https://github.com/coccoc/coccoc-tokenizer/issues/5#issuecomment-504321367_

The `setup.py` file should be changed to something like:
```
from Cython.Distutils import build_ext
from distutils.core import setup
from distutils.extension import Extension

import os
os.environ['CC'] = 'g++'
os.environ['CXX'] = 'g++'

ext_modules = [
    Extension(
        name="CocCocTokenizer",
        sources=["CocCocTokenizer.pyx"],
        extra_compile_args=["-Wno-cpp", "-Wno-unused-function", "-O2", "-march=native", '-stdlib=libc++', '-std=c++11'],
        extra_link_args=["-O2", "-march=native", '-stdlib=libc++'],
        language="c++",
        include_dirs=["."],
    )
]

setup(
    name="coccoc-tokenizer", ext_modules=ext_modules, cmdclass={"build_ext": build_ext}
)
```

**Comment by Prudvi01** [comment]
> Originally posted by @TruongKhang in [coccoc/coccoc-tokenizer#5 (comment)](https://github.com/coccoc/coccoc-tokenizer/issues/5#issuecomment-504321367)_
> 
> The `setup.py` file should be changed to something like:
> 
> ```
> from Cython.Distutils import build_ext
> from distutils.core import setup
> from distutils.extension import Extension
> 
> import os
> os.environ['CC'] = 'g++'
> os.environ['CXX'] = 'g++'
> 
> ext_modules = [
>     Extension(
>         name="CocCocTokenizer",
>         sources=["CocCocTokenizer.pyx"],
>         extra_compile_args=["-Wno-cpp", "-Wno-unused-function", "-O2", "-march=native", '-stdlib=libc++', '-std=c++11'],
>         extra_link_args=["-O2", "-march=native", '-stdlib=libc++'],
>         language="c++",
>         include_dirs=["."],
>     )
> ]
> 
> setup(
>     name="coccoc-tokenizer", ext_modules=ext_modules, cmdclass={"build_ext": build_ext}
> )
> ```

@joshlk Thank you for this. Works perfectly on my mac but shows
`g++: error: unrecognized command line option ‘-stdlib=libc++’
error: command 'g++' failed with exit status 1` 
when I try to compile it on Linux(Ubuntu),

**Comment by lonelykid** [comment]
> Cython does not change anything in the flags and options of your C compiler or linker. The usual ways how these options enter the game are:
> 
> * provided by the user, e.g. by setting `CFLAGS`
> * inherited from the original build flags of CPython itself in `distutils`
> * platform/deployment specific configuration
> 
> AFAICT, none of the effects described in this ticket suggest a problem in Cython.

It can be configured to work with manually added flags for sure. But the default setting only works with gcc; it does not work with llvm/clang. It would be nice to have cython to detect the compiler and choose proper compiler/linker flags.

**Comment by lonelykid** [comment]
https://github.com/pandas-dev/pandas/issues/23424#issuecomment-446393981
I think this comment explains the root reason of the problem. I think such a fix, requiring target macos>10.9, inside cython would be nice to have, given that xcode/clang has such weird behavior and that might be harder to fix.
