### ISSUE TITLE
Cannot assign to struct pointer

### ISSUE THREAD

**Issue by memeplex** [cython/cython#3388]
I'm unable to figure out why this pure-python code is not compiling:

```python
# cython: language_level=3, boundscheck=False, nonecheck=False, initializedcheck=False

import cython as cy
import numpy as np


Point = cy.struct(x=cy.double, y=cy.double,)


@cy.cfunc
def f(ps: Point[:]) -> cy.double:
    x: cy.double = 0
    i: cy.size_t
    for i in range(len(ps)):
        p: cy.pointer(Point) = cy.address(ps[i])
        x += p[0].x
    return x


points = np.recarray(2, [("x", np.float64), ("y", np.float64)])
print(f(points))
```

The error is:

```
@cy.cfunc
def f(ps: Point[:]) -> cy.double:
    x: cy.double = 0
    i: cy.size_t
    for i in range(len(ps)):
        p: cy.pointer(Point) = cy.address(ps[i])
                                ^
------------------------------------------------------------

test.py:15:33: Cannot assign type 'Point *' to 'object *'
```

It looks like  bug to me.

**Comment by memeplex** [comment]
A typedef seems to be a simple workaround:

```
Point_p = cy.typedef(cy.pointer(Point))
```

Still, maybe I'm wrong, but I believe this is a bug. Even worse:

```
import cython as cy


Point = cy.struct(x=cy.double, y=cy.double,)


@cy.cfunc
def g(p: cy.pointer(Point)):
    p[0].x += 1
```

throws

```
@cy.cfunc
def g(p: cy.pointer(Point)):
          ^
------------------------------------------------------------

test.py:10:11: 'pointer' not a valid cython attribute or is being used incorrectly
```

**Comment by rhpvorderman** [comment]
I have the same problem.

```
    cythoning src/isal/isal_zlib.pyx to src/isal/isal_zlib.c
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    cpdef compress(unsigned char *data, int level=ISAL_DEFAULT_COMPRESSION):
        if level == -1:
            level = ISAL_DEFAULT_COMPRESSION
        cdef isal_zstream stream
        cdef isal_zstream * stream_ptr = stream
                                        ^
    ------------------------------------------------------------
    
    src/isal/isal_zlib.pyx:172:37: Cannot assign type 'isal_zstream' to 'isal_zstream *'
```

The struct code is in igzip_lib.pxd:
```
    cdef struct isal_zstream:
        unsigned char *next_in  #!< Next input byte
        unsigned long avail_in  #!< number of bytes available at next_in
        unsigned long total_in_start  #!< total number of bytes read so far
        unsigned char *next_out  #!< Next output byte
        unsigned long avail_out  #!< number of bytes available at next_out
        unsigned long total_out  #!< total number of bytes written so far
        isal_hufftables *hufftables  #!< Huffman encoding used when compressing
        unsigned long level  #!< Compression level to use
        unsigned long level_buf_size  #!< Size of level_buf
        unsigned char * level_buf  #!< User allocated buffer required for different compression levels
        unsigned int end_of_stream  #!< non-zero if this is the last input buffer
        unsigned int flush  #!< Flush type can be NO_FLUSH, SYNC_FLUSH or FULL_FLUSH
        unsigned int gzip_flag  #!< Indicate if gzip compression is to be performed
        unsigned int hist_bits  #!< Log base 2 of maximum lookback distance, 0 is use default
        isal_zstate internal_state  #!< Internal state for this stream
```

Where isal_zstate and isal_hufftables are also structs.

**Comment by da-woods** [comment]
@rhpvorderman You don't have the same problem. You just haven't taken the address of the struct.

`        cdef isal_zstream * stream_ptr = &stream`

**Comment by rhpvorderman** [comment]
@da-woods Thanks for the speedy reply. Sorry for posting this wrongly. This is the first time I use cython to connect to a C-library. I have no previous C experience, so declaring pointers properly is new for me. I read the whole cython documentation but unfortunately able I did not manage to grasp from it how to properly declare a pointer.

Thanks for helping me out.

**Comment by da-woods** [comment]
This seems like it (the pure-Python mode bug with `cy.Pointer`) is fixed in the current alpha. git bisect tells me that it was fixed in ab1d7284f79794d075e79c87df671a87ae8b2b4b. I'd like to take credit but I can't see how that commit relates to this....

(@rhpvorderman If I were you I'd try to learn a bit of C first. The documentation for the "wrapping C" part of Cython does assume that you know C, and you'll find plenty of C-related pitfalls)

**Comment by da-woods** [comment]
> This seems like it (the pure-Python mode bug with `cy.Pointer`) is fixed in the current master. git bisect tells me that it was fixed in [ab1d728](https://github.com/cython/cython/commit/ab1d7284f79794d075e79c87df671a87ae8b2b4b). I'd like to take credit but I can't see how that commit relates to this....

Oh - I reckon it's to do with changing the type inference on indexing memoryviews.

It looks like the second half of the bug (`def g(p: cy.pointer(Point)):`) was fixed in 3dc2b9dfc23638fbef2558d619709b5235d5df08. Again, it seems pretty accidental.

My feeling is neither of these should be backported, although that does leave this bug unfixed.

**Comment by rhpvorderman** [comment]
> (@rhpvorderman If I were you I'd try to learn a bit of C first. The documentation for the "wrapping C" part of Cython does assume that you know C, and you'll find plenty of C-related pitfalls)

Thanks for the advice. I, of course, was hoping to avoid (most of) C altogether but still get access to the raw power of this library by wrapping it. No free lunch for me I guess. I will learn a bit of C and put some 'pointers' in the Cython documentation afterward to useful resources to read when wrapping libraries.

**Comment by scoder** [comment]
> put some 'pointers' in the Cython documentation afterward

Something that could help the documentation would be a [glossary](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary-directive) that certain terms could link to. Pointer would be a good candidate, or C data structures in general. I created #3802, help is welcome.
