### ISSUE TITLE
pandas._libs.reduction.Reducer' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by JASHWANTHREDDYTUPILI** [cython/cython#3408]
import pandas
Traceback (most recent call last):

  File "<ipython-input-4-38d4b0363d82>", line 1, in <module>
    import pandas

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\__init__.py", line 54, in <module>
    from pandas.core.api import (

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py", line 63, in <module>
    from pandas.core.groupby.groupby import (

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 61, in <module>
    from pandas.core.groupby import base, ops

  File "C:\Users\tjash\Anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 16, in <module>
    import pandas._libs.reduction as libreduction

  File "pandas\_libs\reduction.pyx", line 30, in init pandas._libs.reduction

AttributeError: type object 'pandas._libs.reduction.Reducer' has no attribute '__reduce_cython__'

Can some one help me with the above error

**Comment by MomIsBestFriend** [comment]
@JASHWANTHREDDYTUPILI Can you please post this issue in https://github.com/pandas-dev/pandas

**Comment by JASHWANTHREDDYTUPILI** [comment]
I posted it in pandas already . They were looping cython issues and asked me to post here

**Comment by JASHWANTHREDDYTUPILI** [comment]
We don't implement any "reduce_cython" in that module, which suggests that this is bubbling up from cython. cc @scoder.  this was one of the comment posted in pandas

**Comment by MomIsBestFriend** [comment]
> I posted it in pandas already . They were looping cython issues and asked me to post here

@JASHWANTHREDDYTUPILI Sorry, I wasn't aware of that.

**Comment by da-woods** [comment]
This is really a place for bug-reports, not for user support. I'm relatively sure the bug that caused this was fixed a couple of years ago. If I were you I'd update the base Anaconda program:

     conda update -n root conda

Then create and activate a fresh environment with Pandas installed

    conda create --name some_name python3 pandas
    conda activate some_name

**Comment by JASHWANTHREDDYTUPILI** [comment]
Even creating and activating the fresh environment does not solve the error

**Comment by da-woods** [comment]
Unfortunately if I run the exact commands I suggested, open a Python prompt then do `import pandas` it works for me (tested on Windows). I can't help.

**Comment by JASHWANTHREDDYTUPILI** [comment]
I don't understand but Thanks for your valuable time

**Comment by MomIsBestFriend** [comment]
@JASHWANTHREDDYTUPILI I think you should read this:

https://docs.anaconda.com/anaconda/install/update-version/

---

Can the steps described in the mentioned documentation above are possible in your environment?

**Comment by scoder** [comment]
Duplicate of #3545.
