### ISSUE TITLE
CodeWriter doesn't work for 'CFuncDefNode'

### ISSUE THREAD

**Issue by sighingnow** [cython/cython#3513]
```python
>>> writer = CodeWriter()

>>> writer.write(TreeFragment("def fn(): \n    pass").root)
<Cython.CodeWriter.LinesResult at 0x121704a90>

>>> writer.write(TreeFragment("cdef fn(): \n    pass").root)
Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/usr/local/lib/python3.7/site-packages/Cython/CodeWriter.py", line 243, in visit_FuncDefNode
    self.startline(u"def %s(" % node.name)
AttributeError: 'CFuncDefNode' object has no attribute 'name'
```

**Comment by scoder** [comment]
Interesting to see that people are actually using this. :)

PR welcome.

**Comment by sighingnow** [comment]
> Interesting to see that people are actually using this. :)

Is the `CodeWriter` the only way to dump Cython AST into syntastically-correct Cython code?

> PR welcome.

PR #3514 will fix that.

**Comment by scoder** [comment]
> Is the CodeWriter the only way to dump Cython AST into syntastically-correct Cython code?

The intended way, yes.

**Comment by sighingnow** [comment]
@scoder It is quite wired that `CodeWriter` cannot handle some kinkds of experssions, for example, the `PrimaryCmpNode`, however we have a `visit_PrimaryCmpNode` in `ExpressionWriter`.

The `CodeWriter` seems never been used at other place in Cython repo, but due to missing such visitors we cannot have a `Writer` that can print whole program. Should we make `CodeWriter` to inherits from `ExpressionWriter` as well?

**Comment by sighingnow** [comment]
@scoder Any comments? (polite ping 😆

**Comment by scoder** [comment]
@sighingnow good idea. I just pushed #3528.

**Comment by sighingnow** [comment]
> good idea. I just pushed #3528.

Thanks a lot! Visitor for some kinds of ast `Node` are still missing, I will continue to push to #3514 to make the `CodeWriter` more complete. Will ping you when it ready for review and merging.
