### ISSUE TITLE
[BUG] ob_digit is unknown in Python 3.12a

### ISSUE THREAD

**Issue by ThomasWaldmann** [cython/cython#5426]
### Describe the bug

When trying to compile python-llfuse's cython code, it errors out when using it with Python 3.12.0a7 and Cython 0.29.x:

```
src/llfuse.c: In function ‘__Pyx_PyInt_As_time_t’:
src/llfuse.c:58504:53: error: ‘PyLongObject {aka struct _longobject}’ has no member named ‘ob_digit’
             const digit* digits = ((PyLongObject*)x)->ob_digit;
                                                     ^~
```

### Code to reproduce the behaviour:

```
pip install llfuse==1.4.2
```

### OS

Ubuntu Linux 18.04

### Python version

3.12.0a7

### Cython version

0.29.x

### Additional context

Reported there: https://github.com/python-llfuse/python-llfuse/issues/73

**Comment by ThomasWaldmann** [comment]
https://github.com/cython/cython/issues/5238

Looks like this is fixed in cython master branch.

0.29 == ?

**Comment by mattip** [comment]
As far as I can tell, there is no 0.29 release that contains the fix from commit 1c3a212 (the 0.29.x branch still does not have the fix). That commit is part of the 3.0.0b1 and 3.0.0b2 releases, and is also available on master.

**Comment by da-woods** [comment]
For 0.29.x we just disable the `CYTHON_USE_LONG_INTERNALS` macro. So it should work but potentially with a small performance loss

**Comment by ThomasWaldmann** [comment]
Is that the fix? This is in 0.29.34:

https://github.com/cython/cython/commit/3397705da036bb2df4a5b8b4bf08dbad7bdb409f

**Comment by da-woods** [comment]
> Is that the fix? This is in 0.29.34:
> 
> [3397705](https://github.com/cython/cython/commit/3397705da036bb2df4a5b8b4bf08dbad7bdb409f)

Yes that should be it

**Comment by scoder** [comment]
Note that you can always define the C macro to 0 yourself.

**Comment by ThomasWaldmann** [comment]
OK, considering a workaround is in 0.29.34, I guess this could be closed (or kept open a while for better visibility and then closed).

**Comment by da-woods** [comment]
I think it's fixed on both branches to the extent we plan to, so I'll close it
